{{- if .Values.openshift.build.create -}}
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ include "replik8s.name" . }}
  labels:
{{ include "replik8s.labels" . | nindent 4 }}
spec:
  lookupPolicy:
    local: false
{{- end -}}
